PACKAGE_NAME="mt7925-bt-recovery"
PACKAGE_VERSION="0.1"
BUILT_MODULE_NAME[0]="btmtk"
DEST_MODULE_LOCATION[0]="/updates/dkms"
BUILD_EXCLUSIVE_KERNEL="^(6\.([4-9]|[1-9][0-9]+)|[7-9]|[1-9][0-9]+)\."
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
AUTOINSTALL="yes"
